<?php

//////////////////////////////////////////////////////////
// Clears key source parameters to prevent them carrying
// over from one source to the next. This is precaution
// in case these parameters with null or empty values 
// are omitted or deleted for some sources. 
//////////////////////////////////////////////////////////

$source_name_full="";
$source_url="";	
$source_citation="";
$source_contact_name="";
$source_contact_email="";
$date_accessed="";
$focal_regions="";
$cclist_countries="";
$pclist_countries="";
$is_comprehensive=0;
$regional_scope="";
$taxonomic_scope="";
$file_raw = "";
$datapath="";		

?>