<?php

/////////////////////////////////////////////////////////////
// Fixes specific to this source, if any
//
// Leave content between this comment and closing line blank 
// if no source-specific fixes required
/////////////////////////////////////////////////////////////

echo "  Source-specific corrections...";

// Fix non-standard stateProvince codes
$sql="
";
sql_execute_multiple($sql);


echo $done;

?>